### ISSUE TITLE
EROFS: read-only file system, open 'db.json'

### ISSUE THREAD

**Issue by cunguyen-agilityio** [kitloong/json-server-vercel#15] opened 2024-05-02 04:06 UTC
Try to send a post method

Error: EROFS: read-only file system, open 'db.json'
at Object.openSync (node:fs:590:3)
at writeFileSync (node:fs:2202:35)
at FileSync.write (/var/task/node_modules/.pnpm/lowdb@1.0.0/node_modules/lowdb/adapters/FileSync.js:53:14)
at LodashWrapper.db.write (/var/task/node_modules/.pnpm/lowdb@1.0.0/node_modules/lowdb/lib/main.js:37:21)
at /var/task/node_modules/.pnpm/json-server@0.17.4/node_modules/json-server/lib/server/router/write.js:5:8
at Layer.handle [as handle_request]
(/var/task/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
at next (/var/task/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)
at create (/var/task/node_modules/.pnpm/json-server@0.17.4/node_modules/json-server/lib/server/router/plural.js:222:5)
at Layer.handle [as handle_request]
(/var/task/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/layer.js:95:5)
at next (/var/task/node_modules/.pnpm/express@4.18.2/node_modules/express/lib/router/route.js:144:13)

**Comment by kitloong** [comment] 2024-05-02 06:29
Duplicate of #6

**Closed as not planned** 2024-05-02 06:30 UTC
Labels: duplicate
